
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "django"
  namespace: "default"
  labels:
    app: "django"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "django"
  template:
    metadata:
      labels:
        app: "django"
    spec:
      containers:
      - name: "django"
        image: "gcr.io/kubernetes-project-378913/test-project-images:tagversion"
        

        
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "flask-service"
  namespace: "default"
  labels:
    app: "django"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: "django"
  type: "LoadBalancer"
  loadBalancerIP: "" 